services:
  meowshare:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - VITE_API_URL=/api
        - VITE_APP_NAME=${VITE_APP_NAME:-MeowShare}
        - NUGET_APIKEY=${NUGET_APIKEY}
        - NUGET_SOURCE=${NUGET_SOURCE}
    ports:
      - "${FRONTEND_PORT:-80}:80"
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - VITE_APP_NAME=${VITE_APP_NAME:-MeowShare}
    # No network needed for single container

# No need for networks section with single container