FROM node:20-alpine
WORKDIR /app
COPY package.json .
RUN npm install
RUN npm i -g serve
COPY . .
# Pass build-time environment variables to Vite
ARG VITE_API_URL
ENV VITE_API_URL=$VITE_API_URL
RUN npm run build

# Create serve.json configuration file to handle API proxying
RUN echo '{ "rewrites": [{ "source": "/api/**", "destination": "https://backend:8080/api" }] }' > serve.json

EXPOSE 3000
CMD [ "serve", "-s", "dist", "-l", "3000", "--no-clipboard", "--no-request-logging" ]